name: cherokee-wavernn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.4
  - audioread=2.1.9
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - cryptography=35.0.0
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - dbus=1.13.18
  - decorator=5.1.0
  - expat=2.4.1
  - ffmpeg=4.3.2
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.1
  - intel-openmp=2021.4.0
  - jbig=2.1
  - joblib=1.1.0
  - jpeg=9d
  - kiwisolver=1.3.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=2.2.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libdeflate=1.7
  - libffi=3.3
  - libflac=1.3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libllvm11=11.1.0
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.37
  - librosa=0.8.1
  - libsndfile=1.0.31
  - libstdcxx-ng=9.3.0
  - libtiff=4.3.0
  - libuuid=1.0.3
  - libuv=1.40.0
  - libvorbis=1.3.7
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - libzlib=1.2.11
  - llvm-openmp=12.0.1
  - llvmlite=0.37.0
  - lz4-c=1.9.3
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.2
  - nettle=3.6
  - numba=0.54.1
  - numpy=1.20.3
  - numpy-base=1.20.3
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1l
  - packaging=21.3
  - pcre=8.45
  - pillow=7.2.0
  - pip=21.2.4
  - pooch=1.5.2
  - pyopenssl=21.0.0
  - pyparsing=3.0.6
  - pyqt=5.9.2
  - pysocks=1.7.1
  - pysoundfile=0.10.3.post1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.10.0
  - pytorch-mutex=1.0
  - qt=5.9.7
  - readline=8.1
  - requests=2.26.0
  - resampy=0.2.2
  - scikit-learn=1.0.1
  - scipy=1.7.1
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.36.0
  - tbb=2021.4.0
  - threadpoolctl=3.0.0
  - tk=8.6.10
  - torchvision=0.11.1
  - tornado=6.1
  - typing_extensions=3.10.0.2
  - tzdata=2021a
  - urllib3=1.26.7
  - wheel=0.37.0
  - x264=1!161.3030
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - colorlog==6.4.1
    - denoiser==0.1.4
    - hydra-colorlog==0.1.4
    - hydra-core==0.11.3
    - omegaconf==1.4.1
    - progressbar==2.5
    - pycparser==2.20
    - pydub==0.25.1
    - pystoi==0.3.3
    - pyyaml==5.4.1
    - sounddevice==0.4.2
    - torch==1.9.1
    - torchaudio==0.9.1
    - tqdm==4.62.3
